name: Testcontainers nodejs example

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        check-latest: true

    - name: Install dependencies
      run: npm ci

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Run tests with Testcontainers
      run: npm run debug
      env:
        TESTCONTAINERS_DOCKER_IMAGE: postgres:17.2-alpine